// BOSS 配置资料
export const bossConfig = [
  {
    id: "red_diamond_king",
    name: "紅寶王",
    respawnMinutesMin: 23,
    respawnMinutesMax: 30,
    needLocation: false,
    location: ["維多利亞：海岸草叢Ⅲ"],
    description: "23分~30分重生",
    commonLoots: [
      "黃金騎士頭盔",
      "紅色法師帽",
      "黑提貝之帽",
      "黑獵人帽",
      "褐色皮茲頭巾",
      "黑獵人服",
      "黑軍官鎧甲",
      "黑敏捷之服",
      "紅騎士甲",
      "紅打獵服",
      "綠敏捷之服",
      "白魔者之袍",
      "紅魔者之袍",
      "褐色海盜服",
      "黑戰鬥鞋",
      "紅皮製長靴",
      "黑飄風鞋",
      "黑追擊鞋",
      "褐色木鞋",
      "白紋短手套",
      "黑命中手套",
      "黑賢者手套",
      "黑精神手套",
      "褐色堅固皮手腕",
      "海星鏢",
      "彈丸",
      "頭盔防禦卷軸60%",
      "頭盔防禦卷軸10%",
      "耳環智力卷軸60%",
      "耳環智力卷軸10%",
      "上衣防禦卷軸60%",
      "上衣防禦卷軸10%",
      "上衣力量卷軸60%",
      "套服敏捷卷軸60%",
      "褲、裙防禦卷軸60%",
      "盾牌生命卷軸10%",
      "披風智力卷軸60%",
      "腰帶敏捷卷軸100%",
      "腰帶幸運卷軸100%",
      "單手劍攻擊卷軸10%",
      "單手斧攻擊卷軸10%",
      "單手棍攻擊卷軸60%",
      "短劍攻擊卷軸10%",
      "短杖魔力卷軸60%",
      "短杖魔力卷軸10%",
      "長杖魔力卷軸60%",
      "雙手劍攻擊卷軸60%",
      "矛命中卷軸10%",
      "指虎攻擊卷軸60%",
      "火槍攻擊卷軸10%",
    ],
  },

  {
    id: "tree_queen",
    name: "樹妖王",
    respawnMinutesMin: 23,
    respawnMinutesMax: 30,
    needLocation: false,
    location: ["維多利亞：東方岩石山Ⅴ"],
    description: "23分~30分重生",
    commonLoots: [
      "黃金諾曼頭盔",
      "黑魔道之帽",
      "黑羽絲絨帽",
      "黑海盜頭巾",
      "紅色皇家頭巾",
      "枯葉耳環",
      "黑貴族之服",
      "紫金鎧甲(紫鎮日鎧甲)",
      "深夜之影",
      "黑女貴族服",
      "黑鎮月鎧甲",
      "黑星光長袍",
      "黑色月光服",
      "紅色麻布衣",
      "紅流星鞋",
      "黑月鞋",
      "紅精靈鞋",
      "紫金月鞋",
      "褐色尖頭皮鞋",
      "黑色長手套",
      "黑精靈手套",
      "黑勇氣手套",
      "黑盜賊手套",
      "褐色瑞恩手腕",
      "米伽勒的平底鍋",
      "木製陀螺",
      "枯木樹液",
      "上衣防禦卷軸10%",
      "套服敏捷卷軸10%",
      "褲、裙防禦卷軸10%(下衣防禦力卷軸10%)",
      "鞋子敏捷卷軸60%",
      "手套敏捷卷軸60%",
      "盾牌防禦卷軸60%",
      "披風魔防卷軸60%",
      "披風防禦卷軸60%",
      "披風魔力卷軸60%",
      "披風智力卷軸60%",
      "披風智力卷軸10%",
      "腰帶力量卷軸100%",
      "腰帶智力卷軸100%",
      "單手劍攻擊卷軸60%",
      "單手斧攻擊卷軸60%",
      "單手棍攻擊卷軸60%",
      "雙手劍攻擊卷軸10%",
      "雙手斧命中卷軸60%",
      "矛命中卷軸60%",
    ],
  },

  {
    id: "zombie_monkey_king",
    name: "殭屍猴王",
    respawnMinutesMin: 38,
    respawnMinutesMax: 45,
    needLocation: false,
    location: ["維多利亞：巫婆森林Ⅰ"],
    description: "38分~45分重生",
    commonLoots: [
      "樹靈之劍",
      "樹靈之斧",
      "古代錘",
      "破碎刃",
      "大魔法師短杖",
      "白龍之杖",
      "黃金杖",
      "虎劍",
      "太陽之斧",
      "黃金錘",
      "丈八蛇矛",
      "釣魚杆",
      "九龍刀",
      "天弓",
      "炎弩",
      "黑手甲",
      "惡魔之爪",
      "拉斯菲特之槍",
      "項鍊敏捷卷軸100%",
      "項鍊幸運卷軸100%",
      "耳環智力卷軸60%",
      "套服防禦卷軸60%",
      "鞋子速度卷軸60%",
      "手套敏捷卷軸60%",
      "盾牌防禦卷軸60%",
      "盾牌力量卷軸60%",
      "披風智力卷軸60%",
      "長杖魔力卷軸60%",
      "雙手斧攻擊卷軸60%",
      "弩攻擊卷軸60%",
      "拳套攻擊卷軸60%",
      "火槍攻擊卷軸60%",
      "套服智力卷軸10%",
      "盾牌生命卷軸10%",
      "披風魔防卷軸10%",
      "披風智力卷軸10%",
      "短杖魔力卷軸10%",
      "槍攻擊卷軸10%",
      "指虎攻擊卷軸10%",
    ],
  },

  {
    id: "jelly_king",
    name: "巨居蟹",
    respawnMinutesMin: 45,
    respawnMinutesMax: 60,
    needLocation: false,
    location: ["黃金海岸：海龜沙灘"],
    description: "45分~1小時重生",
    commonLoots: [
      "將軍的紅頭盔",
      "黑和平之帽",
      "黑忍者頭巾",
      "黑弓羽",
      "紫色亞麻水手頭巾",
      "紅鋼玉鎧甲",
      "黑鋼玉鎧甲",
      "黑飛影之服",
      "赤飛影之服",
      "黑神聖服",
      "赤旋風甲",
      "赤草露",
      "黑聖黨之服",
      "紫色皇家套裝",
      "赤飛影之褲",
      "粉紅天使鞋",
      "紫花精鞋",
      "紅十字鞋",
      "黑無痕之鞋",
      "黑色巴西里靴",
      "黑戰鬥手套",
      "黑封印手套",
      "黑神功手套",
      "黃金柔絲手套",
      "黑色舒爾特手套",
      "黑游泳圈",
      "救生圈",
      "彩虹游泳圈",
      "眼飾力量卷軸100%",
      "眼飾智力卷軸100%",
      "頭盔生命卷軸60%",
      "套服智力卷軸60%",
      "鞋子跳躍卷軸60%",
      "鞋子速度卷軸60%",
      "手套攻擊卷軸60%",
      "披風力量卷軸60%",
      "披風幸運卷軸60%",
      "弩攻擊卷軸60%",
      "拳套攻擊卷軸60%",
      "鞋子敏捷卷軸10%",
      "手套敏捷卷軸10%",
      "盾牌防禦卷軸10%",
      "披風魔防卷軸10%",
      "單手劍攻擊卷軸10%",
    ],
  },

  {
    id: "ghost_king",
    name: "冥界幽靈",
    respawnMinutesMin: 45,
    respawnMinutesMax: 60,
    needLocation: true,
    location: ["維多利亞：地鐵一號線[地區04]", "維多利亞：地鐵二號線[地區03]"],
    description: "45分~1小時重生",
    commonLoots: [],
  },

  {
    id: "clock_king",
    name: "咕咕鐘",
    respawnMinutesMin: 68,
    respawnMinutesMax: 90,
    needLocation: false,
    location: ["玩具城：時間之路<3>"],
    description: "1小時8分~1小時30分重生",
    commonLoots: [],
  },

  {
    id: "doll_king",
    name: "仙人娃娃",
    respawnMinutesMin: 158,
    respawnMinutesMax: 180,
    needLocation: false,
    location: ["桃花仙境：上級修煉場"],
    description: "2小時38分~3小時重生",
    commonLoots: [],
  },

  {
    id: "cat_king",
    name: "喵怪仙人",
    respawnMinutesMin: 150,
    respawnMinutesMax: 170,
    needLocation: false,
    location: ["桃花仙境：妖怪之林"],
    description: "2小時30分~2小時50分重生",
    commonLoots: [],
  },

  {
    id: "mushroom_king",
    name: "蘑菇王",
    respawnMinutesMin: 210,
    respawnMinutesMax: 240,
    needLocation: false,
    location: ["隱藏地圖：菇菇王出沒地"],
    description: "3小時30分~4小時重生",
    commonLoots: [],
  },

  {
    id: "book_king",
    name: "書生幽靈",
    respawnMinutesMin: 150,
    respawnMinutesMax: 300,
    needLocation: false,
    location: ["童話村：狐狸山坡"],
    description: "2小時30分~5小時重生",
    commonLoots: [],
  },

  {
    id: "ginseng_king",
    name: "巨大深山人蔘",
    respawnMinutesMin: 60,
    respawnMinutesMax: 135,
    needLocation: false,
    location: ["靈藥幻境：豐饒的藥草田"],
    description: "1小時~2小時15分重生",
    commonLoots: [],
  },

  {
    id: "snow_queen",
    name: "雪山魔女",
    respawnMinutesMin: 168,
    respawnMinutesMax: 180,
    needLocation: true,
    location: ["冰原雪域：冰面Ⅰ", "冰原雪域：冰面Ⅱ", "冰原雪域：寒冰平原"],
    description: "2小時38分~3小時",
    commonLoots: [],
  },

  {
    id: "crocodile_king",
    name: "沼澤巨鱷",
    respawnMinutesMin: 90,
    respawnMinutesMax: 105,
    needLocation: false,
    location: ["維多利亞：危險的黑鱷魚1"],
    description: "1小時30分~1小時45分重生",
    commonLoots: [],
  },

  {
    id: "zombie_mushroom_king",
    name: "殭屍蘑菇王",
    respawnMinutesMin: 195,
    respawnMinutesMax: 225,
    needLocation: false,
    location: ["維多利亞：蘑菇王之墓"],
    description: "3小時15分~3小時45分重生",
    commonLoots: [],
  },

  {
    id: "dead_god",
    name: "厄運死神",
    respawnMinutesMin: 45,
    respawnMinutesMax: 105,
    needLocation: true,
    location: [
      "冰原雪域：亡者之林Ⅰ",
      "冰原雪域：亡者之林Ⅱ",
      "冰原雪域：亡者之林Ⅲ",
      "冰原雪域：亡者之林Ⅳ",
    ],
    description: "45分~1小時45分重生",
    commonLoots: [],
  },

  {
    id: "golem_king",
    name: "葛雷金剛",
    respawnMinutesMin: 270,
    respawnMinutesMax: 350,
    needLocation: false,
    location: ["地球防衛總部：葛雷之谷"],
    description: "4小時30分~5小時50分",
    commonLoots: [],
  },

  {
    id: "fox_king",
    name: "九尾妖狐",
    respawnMinutesMin: 210,
    respawnMinutesMax: 570,
    needLocation: false,
    location: ["童話村：狐狸山坡"],
    description: "3小時30分~9小時30分重生",
    commonLoots: [],
  },

  {
    id: "kent_king",
    name: "肯德熊",
    respawnMinutesMin: 113,
    respawnMinutesMax: 128,
    needLocation: false,
    location: ["桃花仙境：流浪熊的領土"],
    description: "1小時53分~2小時8分重生",
    commonLoots: [],
  },

  {
    id: "baroque_king",
    name: "巴洛古",
    respawnMinutesMin: 405,
    respawnMinutesMax: 540,
    needLocation: false,
    location: ["維多利亞：被詛咒的寺院"],
    description: "6小時45分~9小時重生",
    commonLoots: [],
  },

  {
    id: "aligee_king",
    name: "艾利傑",
    respawnMinutesMin: 118,
    respawnMinutesMax: 128,
    needLocation: false,
    location: ["天空之城：天空階梯 II"],
    description: "1小時58分~2小時8分重生",
    commonLoots: [],
  },

  {
    id: "black_wheel_king",
    name: "黑輪王",
    respawnMinutesMin: 780,
    respawnMinutesMax: 1020,
    needLocation: true,
    location: ["西門町：夜市徒步區7", "西門町：夜市徒步區7-1"],
    description: "13小時~17小時重生",
    commonLoots: [],
  },

  {
    id: "snow_monster",
    name: "雪毛怪人",
    respawnMinutesMin: 45,
    respawnMinutesMax: 68,
    needLocation: false,
    location: ["冰原雪域：雪人之谷"],
    description: "45分~1小時8分重生",
    commonLoots: [],
  },

  {
    id: "crazy_cat_king",
    name: "瘋狂喵z客",
    respawnMinutesMin: 120,
    respawnMinutesMax: 420,
    needLocation: false,
    location: ["台北101：名人大道西部區域"],
    description: "2小時~7小時重生",
    commonLoots: [],
  },

  {
    id: "sea_monster",
    name: "海怒斯",
    respawnMinutesMin: 180,
    respawnMinutesMax: 300,
    needLocation: false,
    location: ["水世界：海怒斯洞穴"],
    description: "3小時~5小時重生",
    commonLoots: [],
  },

  {
    id: "samurai_king",
    name: "竹刀武士",
    respawnMinutesMin: 113,
    respawnMinutesMax: 128,
    needLocation: false,
    location: ["日本 古代神社：暗夜松林"],
    description: "1小時53分~2小時8分重生",
    commonLoots: [],
  },

  {
    id: "blue_mushroom_king",
    name: "藍色蘑菇王",
    respawnMinutesMin: 720,
    respawnMinutesMax: 1680,
    needLocation: false,
    location: ["日本 古代神社：天皇殿堂"],
    description: "12小時~28小時重生",
    commonLoots: [],
  },

  {
    id: "fire_dragon_king",
    name: "噴火龍",
    respawnMinutesMin: 60,
    respawnMinutesMax: 60,
    needLocation: false,
    location: ["神木村：噴火龍的森林"],
    description: "1小時重生",
    commonLoots: [],
  },

  {
    id: "gryphon_king",
    name: "格瑞芬多",
    respawnMinutesMin: 60,
    respawnMinutesMax: 60,
    needLocation: false,
    location: ["神木村：格瑞芬多森林"],
    description: "1小時重生",
    commonLoots: [],
  },

  {
    id: "ice_dragon_king",
    name: "寒霜冰龍",
    respawnMinutesMin: 240,
    respawnMinutesMax: 720,
    needLocation: false,
    location: ["神木村：深山凶屋"],
    description: "4小時~12小時重生",
    commonLoots: [],
  },

  {
    id: "cactus_king",
    name: "仙人長老",
    respawnMinutesMin: 68,
    respawnMinutesMax: 90,
    needLocation: false,
    location: ["納希綠洲城：仙人掌沙漠2"],
    description: "1小時8分~1小時30分重生",
    commonLoots: [],
  },

  {
    id: "red_blue_king",
    name: "紅藍雙怪",
    respawnMinutesMin: 113,
    respawnMinutesMax: 125,
    needLocation: true,
    location: [
      "瑪迦提亞城：研究所B-1區",
      "瑪迦提亞城：研究所B-3區",
      "瑪迦提亞城：研究所C-2區",
    ],
    description: "1小時53分~2小時5分重生",
    commonLoots: [],
  },

  {
    id: "automatic_security_system",
    name: "自動警備系統",
    respawnMinutesMin: 158,
    respawnMinutesMax: 173,
    needLocation: false,
    location: ["瑪迦提亞城：研究所C-3區"],
    description: "2小時38分~2小時53分重生",
    commonLoots: [],
  },

  {
    id: "diet_and_loyd_king",
    name: "迪特和洛伊德",
    respawnMinutesMin: 150,
    respawnMinutesMax: 165,
    needLocation: false,
    location: ["瑪迦提亞城：研究所202號房"],
    description: "2小時30分~2小時45分重生",
    commonLoots: [],
  },

  {
    id: "chimera_king",
    name: "奇美拉",
    respawnMinutesMin: 120,
    respawnMinutesMax: 135,
    needLocation: false,
    location: ["納希沙漠：祕密通道"],
    description: "2小時~2小時15分重生",
    commonLoots: [],
  },
];

// 獲取所有掉落物列表（用於自動完成提示）
export const getAllLoots = () => {
  const allLoots = new Set();
  bossConfig.forEach((boss) => {
    boss.commonLoots?.forEach((loot) => allLoots.add(loot));
    boss.rareLoots?.forEach((loot) => allLoots.add(loot));
  });
  return Array.from(allLoots).sort();
};

// 根據 BOSS ID 獲取掉落物
export const getLootsByBossId = (bossId) => {
  const boss = bossConfig.find((b) => b.id === bossId);
  if (!boss) return [];
  return [...(boss.commonLoots || []), ...(boss.rareLoots || [])];
};

// 根據 BOSS ID 獲取 BOSS 配置
export const getBossById = (bossId) => {
  return bossConfig.find((b) => b.id === bossId);
};
